name: pln_mobile_design_system
description: "A new Flutter package project."
version: 0.0.1
homepage: null

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  custom_refresh_indicator: ^4.0.1
  flutter:
    sdk: flutter
  flutter_markdown_plus: ^1.0.7
  flutter_svg: ^2.2.4
  lottie: ^3.3.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  assets:
    - assets/animations/gif/
    - assets/animations/lottie/
    - assets/fonts/
    - assets/icons/png/
    - assets/icons/svg/
    - assets/icons/svg/colored/
    - assets/icons/svg/menu/
    - assets/icons/svg/outlined/
    - assets/icons/svg/solid/
    - assets/images/png/
    - assets/images/png/backgrounds/
    - assets/images/png/mascot/
    - assets/images/svg/
    - assets/sounds/

  fonts:
    - family: Figtree
      fonts:
        - asset: assets/fonts/Figtree-Regular.ttf
          weight: 400
        - asset: assets/fonts/Figtree-Medium.ttf
          weight: 500
        - asset: assets/fonts/Figtree-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Figtree-Bold.ttf
          weight: 700
    - family: Fustat
      fonts:
        - asset: assets/fonts/Fustat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Fustat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Fustat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Fustat-Bold.ttf
          weight: 700
